### PR TITLE
HACK: fix hot-looping in naming controller

### PR DESCRIPTION
**Pull request by ncdc**
Fix an issue where the naming controller was hot looping trying to
enqueue other CRDs in the same API group.

With the change to cache.MetaNamespaceKeyFunc to now encode the cluster
name as part of the string key, we have to make a similar change to the
naming controller so that it decodes the cluster name from the key and
reinserts it when enqueuing new items.

Signed-off-by: Andy Goldstein <andy.goldstein@redhat.com>

### CODE REVIEW

**Comment by ncdc** [comment]
cc @sttts

**Comment by ncdc** [comment]
Note, I needed this on Steve's #8 branch that goes with https://github.com/kcp-dev/kcp/pull/175; otherwise, I had unhappy CPU fans.

**Comment by sttts** [comment]
Looks reasonable.

**Review by davidfestal — APPROVED** [review]
Thanks @ncdc for spotting and fixing this bug.

**Comment by ncdc** [comment]
👍 😄 

Not sure what you all have been doing for merges, but I prefer not to self-merge, so please merge when ready. Thanks!

**Comment by davidfestal** [comment]
@stevekuznetsov do you want to review it as well before merging ?

**Pull request merged**
