### PR TITLE
HACK: Make metadata client logical-cluster aware

### PR DESCRIPTION
**Pull request by astefanutti**
/cc @ncdc

### CODE REVIEW

**Comment by ncdc** [comment]
@sttts does your #54 replace this?

**Comment by astefanutti** [comment]
> @sttts does your #54 replace this?

Yes, #54 supersedes this PR. Let me close it.

**Comment by astefanutti** [comment]
> @sttts does your #54 replace this?

Yes, #54 supersedes this PR. Let me close it.

**Comment by sttts** [comment]
Oh, wasn't aware of your PR.

**Comment by astefanutti** [comment]
No worries, yours looks better with only changing `makeURLSegments` 👍🏼.

**Pull request closed without merging**
