### PR TITLE
UPSTREAM: <carry>: scope cluster_authentication_trust_controller properly

### PR DESCRIPTION
**Pull request by ncdc**

### CODE REVIEW

**Comment by ncdc** [comment]
Going to see if I can make this less invasive

**Comment by ncdc** [comment]
```diff
diff --git a/pkg/controlplane/controller/clusterauthenticationtrust/cluster_authentication_trust_controller.go b/pkg/controlplane/controller/clusterauthenticationtrust/cluster_authentication_trust_controller.go
index dcfb67d3887..fa7b64d044b 100644
--- a/pkg/controlplane/controller/clusterauthenticationtrust/cluster_authentication_trust_controller.go
+++ b/pkg/controlplane/controller/clusterauthenticationtrust/cluster_authentication_trust_controller.go
@@ -134,7 +134,7 @@ func NewClusterAuthenticationTrustController(requiredAuthenticationData ClusterA
 }
 
 func (c *Controller) syncConfigMap() error {
-	originalAuthConfigMap, err := c.configMapLister.ConfigMaps(configMapNamespace).Get(configMapName)
+	originalAuthConfigMap, err := c.configMapLister.ConfigMaps(configMapNamespace).Get("root|" + configMapName)
 	if apierrors.IsNotFound(err) {
 		originalAuthConfigMap = &corev1.ConfigMap{
 			ObjectMeta: metav1.ObjectMeta{Namespace: configMapNamespace, Name: configMapName},
```

is a much smaller fix...

**Comment by ncdc** [comment]
Chatted on Slack with @stevekuznetsov - he prefers the larger fix vs. messing with keys

**Review by nrb — COMMENTED** [review]
/lgtm

**Review by nrb — APPROVED** [review]

**Pull request merged**
