### PR TITLE
update structured-merge-diff to 4.2.3

### PR DESCRIPTION
**Pull request by aojea**
/kind bug
```release-note
NONE
```

ref https://github.com/kubernetes/kubernetes/issues/109099

### CODE REVIEW

**Comment by ncdc** [comment]
@aojea thanks! Please rewrite the commit message in the format `UPSTREAM: 109099: <description>`

**Comment by ncdc** [comment]
Then please create a proof PR in kcp where you edit all the go.mod `replace` directives for kube to point to your fork+branch (use hack/bump-k8s.sh to do it - see script for variable names). Once that is green, we can merge this PR, then update your kcp PR to pull in the updated feature-logical-clusters-1.24 branch.

**Comment by aojea** [comment]
> Then please create a proof PR in kcp where you edit all the go.mod `replace` directives for kube to point to your fork+branch (use hack/bump-k8s.sh to do it - see script for variable names). Once that is green, we can merge this PR, then update your kcp PR to pull in the updated feature-logical-clusters-1.24 branch.

https://github.com/kcp-dev/kcp/pull/1804

**Comment by ncdc** [comment]
@aojea please rebase this branch on top of the current `feature-logical-clusters-1.24` to pick up https://github.com/kcp-dev/kubernetes/commit/3e6f8be5ec670cc05127182585f447c0684a0577, then bump https://github.com/kcp-dev/kcp/pull/1804 to pick up the new commit

**Comment by aojea** [comment]
I

**Pull request closed without merging**
